name: smart_budget
description: SmartBudget Flutter Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.2.7

  # Local Storage
  shared_preferences: ^2.3.2

  # Drift SQLite
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24

  path_provider: ^2.1.4
  path: ^1.9.0

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.1

  # Networking
  chopper: ^8.0.1

  # JSON Serialization
  json_annotation: ^4.9.0

  # Charts
  fl_chart: ^0.69.0

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  chopper_generator: ^8.0.1
  drift_dev: ^2.20.2

flutter:
  uses-material-design: true