// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoMF9Igyyswkd2kTVnHVHwJ-zJeJ3nGQI',
    appId: '1:930164032890:web:d5dc22e6d8484b61eac2c3',
    messagingSenderId: '930164032890',
    projectId: 'smartbudget-89e89',
    authDomain: 'smartbudget-89e89.firebaseapp.com',
    storageBucket: 'smartbudget-89e89.firebasestorage.app',
    measurementId: 'G-MS73MQYMGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT2es9HFvY3kTB8EJdipR1r5Bu565B54w',
    appId: '1:930164032890:android:9fcb764dd0027a6feac2c3',
    messagingSenderId: '930164032890',
    projectId: 'smartbudget-89e89',
    storageBucket: 'smartbudget-89e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrp9me8TcQcV6hxXsmIm2HRt39Cu4aXU',
    appId: '1:930164032890:ios:cce28be20056cb86eac2c3',
    messagingSenderId: '930164032890',
    projectId: 'smartbudget-89e89',
    storageBucket: 'smartbudget-89e89.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOrp9me8TcQcV6hxXsmIm2HRt39Cu4aXU',
    appId: '1:930164032890:ios:cce28be20056cb86eac2c3',
    messagingSenderId: '930164032890',
    projectId: 'smartbudget-89e89',
    storageBucket: 'smartbudget-89e89.firebasestorage.app',
    iosBundleId: 'com.example.smartBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoMF9Igyyswkd2kTVnHVHwJ-zJeJ3nGQI',
    appId: '1:930164032890:web:5531d6e7b1b4b6b6eac2c3',
    messagingSenderId: '930164032890',
    projectId: 'smartbudget-89e89',
    authDomain: 'smartbudget-89e89.firebaseapp.com',
    storageBucket: 'smartbudget-89e89.firebasestorage.app',
    measurementId: 'G-SXHJFH4QCQ',
  );
}
